# Generated by Django 5.2.4 on 2025-08-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d/', verbose_name='تصویر دسته\u200cبندی'),
        ),
    ]
